---
- platform: wifi_info
  ip_address:
    name: "${mac} IP Address"
    id: ip
    entity_category: diagnostic
    icon: "mdi:ip"
  ssid:
    name: "${mac} Network Name SSID"
    entity_category: diagnostic
    icon: "mdi:wifi-marker"
  bssid:
    name: "${mac} Router MAC BSSID"
    entity_category: diagnostic
    icon: "mdi:hexadecimal"
  mac_address:
    name: "${mac} Device MAC"
    entity_category: diagnostic
    icon: "mdi:hexadecimal"

