---
- platform: pmsx003
  type: PMSX003

  pm_1_0:
    name: "${node_name} Particulate Matter <1.0µm Concentration"
    id: pm1
    icon: mdi:chemical-weapon
    filters:
      - sliding_window_moving_average:
          window_size: 30
          send_every: 30

  pm_2_5:
    name: "${node_name} Particulate Matter <2.5µm Concentration"
    id: pm2_5
    icon: mdi:chemical-weapon
    filters:
      - sliding_window_moving_average:
          window_size: 30
          send_every: 30

  pm_10_0:
    name: "${node_name} Particulate Matter <10.0µm Concentration"
    id: pm10
    icon: mdi:chemical-weapon
    filters:
      - sliding_window_moving_average:
          window_size: 30
          send_every: 30
