---
blank_issues_enabled: false

contact_links:
  - name: Get help on ESPHome Discord
    url: https://discord.gg/KhAMKrd
    about: Have a question? Not sure if your issue affects everyone reproducibly?
