---
substitutions:
  node_name: weatherstation
  friendly_name: "Weather Station"
  pin_led_status: GPIO21
  pin_i2c: GPIO18
  pin_uart_rx: GPIO17
  pin_uart_tx: GPIO16
  board: "nodemcu-32s"
  platform: "ESP32"

packages:
  wifi: !include ../common/network.yaml
  device_base: !include ../common/device_base.yaml
#   # time: !include .time.yaml
#   # uptime_days: !include .uptime_in_days.yaml

############

logger:
  level: verbose

# PMSX003
uart:
  rx_pin: ${pin_uart_rx}
  tx_pin: ${pin_uart_tx}
  baud_rate: 9600

as3935_i2c:
  irq_pin: ${pin_i2c}

i2c:

# see https://esphome.io/components/sensor/bme680_bsec.html
bme680_bsec:
  address: 0x76
  temperature_offset: 0
  iaq_mode: static
  sample_rate: lp
  state_save_interval: 2h

# dallas:
#   - pin: GPIO13

binary_sensor:
  - <<: !include ../common/binary_sensor/connectivity.yaml
  - <<: !include ../common/binary_sensor/as3935.yaml

text_sensor:
  - <<: !include ../common/text_sensor/wifi.yaml
  - <<: !include ../common/text_sensor/bme680.yaml
  - <<: !include ../common/text_sensor/uptime.yaml

sensor:
  - <<: !include ../common/sensor/wifi.yaml
  - <<: !include ../common/sensor/bme680.yaml
  - <<: !include ../common/sensor/uptime.yaml
  - <<: !include ../common/sensor/PMS5003.yaml
  - <<: !include ../common/sensor/as3935.yaml
  # - <<: !include ../common/sensor/aqi.yaml

time:
  - <<: !include ../common/time/sync-homeassistant.yaml
  - <<: !include ../common/time/sync-sntp.yaml

# script:
#   - <<: !include ../common/script/aqi.yml

sun:
  latitude: !secret latitude
  longitude: !secret longitude
