---
substitutions:
  node_name: base
  mac: 'C0FFEE'
  release_id: 99999999

  pin_led_status: GPIO25
  pin_i2c: GPIO18
  pin_uart_rx: GPIO17
  pin_uart_tx: GPIO16
  board: 'esp32dev'
  platform: 'ESP32'
  flash_write_interval: 5min
  log_level: INFO

  # BMXX80
  bosch_sample_rate: lp # ulp
  bme680_temperature_offset: '0'

  # deep sleep
  run_duration: 60s
  sleep_duration: 5min

esphome:
  name: ${node_name}
  name_add_mac_suffix: true
  project:
    name: 'stefancrain.${node_name}'
    version: ${release_id}
  board: ${board}
  platform: ${platform}
  on_boot:
    then:
      - deep_sleep.prevent: deep_sleep_control
  on_shutdown:
    then:
      - lambda: |-
          id(ts_saved) = id(homeassistant_time).now().timestamp;

preferences:
  flash_write_interval: '${flash_write_interval}'

logger:
  level: '${log_level}'
  logs:
    switch: INFO
    light: WARN

ota:
  password: !secret ota_password

api:
  password: !secret api_password

light:
  - platform: status_led
    name: '${mac} Status LED'
    pin: '${pin_led_status}'
    restore_mode: ALWAYS_OFF

web_server:
  port: 80

packages:
  wifi: !include packages/network.yaml
  deep_sleep: !include packages/deep_sleep.yaml
  globals: !include packages/globals.yaml

binary_sensor:
  - <<: !include binary_sensor/connectivity.yaml
  - <<: !include binary_sensor/deep_sleep.yaml

text_sensor:
  - <<: !include text_sensor/wifi.yaml
  - <<: !include text_sensor/uptime.yaml

sensor:
  - <<: !include sensor/wifi.yaml
  - <<: !include sensor/uptime.yaml

time:
  - <<: !include time/sync-homeassistant.yaml
  - <<: !include time/sync-sntp.yaml

script:
  - <<: !include script/deep_sleep.yaml

sun:
  latitude: !secret latitude
  longitude: !secret longitude
