---
name: ci
on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

jobs:
  yamllint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: yaml-lint
        uses: karancode/yamllint-github-action@master
        with:
          yamllint_config_filepath: .github/lint/.yamllint.yaml
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
